### ISSUE TITLE
Request token iframe style bug, same as AW

### ISSUE THREAD

**Issue by Aaron-P** [Tacklr/CacheManager#12]
Need to fix the inline style on the request token iframe.

**Comment by IDisposable** [comment]
Not sure what AW #12 being referenced was (looks like something else entirely to me). Could you give me more information?

**Comment by Aaron-P** [comment]
Remember on AlertWire we had the scroll bar popping up when the iframe was injected, I think this is going to have the same issue because the inline style of the iframe we are using doesn't have the position absolute and other things that were added to prevent it.

**Comment by IDisposable** [comment]
Oh yeah, that :)
